class StackOverflow(Exception):
    def __init__(self):
        pass


class StackUnderflow(Exception):
    def __init__(self):
        pass